/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE VELOCITY_LIMITS PACKING
package com.MAVLink.development;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Current limits for horizontal speed, vertical speed and yaw rate, as set by SET_VELOCITY_LIMITS.
 */
public class msg_velocity_limits extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_VELOCITY_LIMITS = 355;
    public static final int MAVLINK_MSG_LENGTH = 12;
    private static final long serialVersionUID = MAVLINK_MSG_ID_VELOCITY_LIMITS;

    
    /**
     * Limit for horizontal movement in MAV_FRAME_LOCAL_NED. NaN: No limit applied
     */
    @Description("Limit for horizontal movement in MAV_FRAME_LOCAL_NED. NaN: No limit applied")
    @Units("m/s")
    public float horizontal_speed_limit;
    
    /**
     * Limit for vertical movement in MAV_FRAME_LOCAL_NED. NaN: No limit applied
     */
    @Description("Limit for vertical movement in MAV_FRAME_LOCAL_NED. NaN: No limit applied")
    @Units("m/s")
    public float vertical_speed_limit;
    
    /**
     * Limit for vehicle turn rate around its yaw axis. NaN: No limit applied
     */
    @Description("Limit for vehicle turn rate around its yaw axis. NaN: No limit applied")
    @Units("rad/s")
    public float yaw_rate_limit;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_VELOCITY_LIMITS;

        packet.payload.putFloat(horizontal_speed_limit);
        packet.payload.putFloat(vertical_speed_limit);
        packet.payload.putFloat(yaw_rate_limit);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a velocity_limits message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.horizontal_speed_limit = payload.getFloat();
        this.vertical_speed_limit = payload.getFloat();
        this.yaw_rate_limit = payload.getFloat();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_velocity_limits() {
        this.msgid = MAVLINK_MSG_ID_VELOCITY_LIMITS;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_velocity_limits( float horizontal_speed_limit, float vertical_speed_limit, float yaw_rate_limit) {
        this.msgid = MAVLINK_MSG_ID_VELOCITY_LIMITS;

        this.horizontal_speed_limit = horizontal_speed_limit;
        this.vertical_speed_limit = vertical_speed_limit;
        this.yaw_rate_limit = yaw_rate_limit;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_velocity_limits( float horizontal_speed_limit, float vertical_speed_limit, float yaw_rate_limit, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_VELOCITY_LIMITS;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.horizontal_speed_limit = horizontal_speed_limit;
        this.vertical_speed_limit = vertical_speed_limit;
        this.yaw_rate_limit = yaw_rate_limit;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_velocity_limits(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_VELOCITY_LIMITS;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

          
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_VELOCITY_LIMITS - sysid:"+sysid+" compid:"+compid+" horizontal_speed_limit:"+horizontal_speed_limit+" vertical_speed_limit:"+vertical_speed_limit+" yaw_rate_limit:"+yaw_rate_limit+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_VELOCITY_LIMITS";
    }
}
        