/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SET_VELOCITY_LIMITS PACKING
package com.MAVLink.development;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Set temporary maximum limits for horizontal speed, vertical speed and yaw rate.
        The consumer must stream the current limits in VELOCITY_LIMITS at 1 Hz or more (when limits are being set).
        The consumer should latch the limits until a new limit is received or the mode is changed.
      
 */
public class msg_set_velocity_limits extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_SET_VELOCITY_LIMITS = 354;
    public static final int MAVLINK_MSG_LENGTH = 14;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SET_VELOCITY_LIMITS;

    
    /**
     * Limit for horizontal movement in MAV_FRAME_LOCAL_NED. NaN: Field not used (ignore)
     */
    @Description("Limit for horizontal movement in MAV_FRAME_LOCAL_NED. NaN: Field not used (ignore)")
    @Units("m/s")
    public float horizontal_speed_limit;
    
    /**
     * Limit for vertical movement in MAV_FRAME_LOCAL_NED. NaN: Field not used (ignore)
     */
    @Description("Limit for vertical movement in MAV_FRAME_LOCAL_NED. NaN: Field not used (ignore)")
    @Units("m/s")
    public float vertical_speed_limit;
    
    /**
     * Limit for vehicle turn rate around its yaw axis. NaN: Field not used (ignore)
     */
    @Description("Limit for vehicle turn rate around its yaw axis. NaN: Field not used (ignore)")
    @Units("rad/s")
    public float yaw_rate_limit;
    
    /**
     * System ID (0 for broadcast).
     */
    @Description("System ID (0 for broadcast).")
    @Units("")
    public short target_system;
    
    /**
     * Component ID (0 for broadcast).
     */
    @Description("Component ID (0 for broadcast).")
    @Units("")
    public short target_component;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_SET_VELOCITY_LIMITS;

        packet.payload.putFloat(horizontal_speed_limit);
        packet.payload.putFloat(vertical_speed_limit);
        packet.payload.putFloat(yaw_rate_limit);
        packet.payload.putUnsignedByte(target_system);
        packet.payload.putUnsignedByte(target_component);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a set_velocity_limits message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.horizontal_speed_limit = payload.getFloat();
        this.vertical_speed_limit = payload.getFloat();
        this.yaw_rate_limit = payload.getFloat();
        this.target_system = payload.getUnsignedByte();
        this.target_component = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_set_velocity_limits() {
        this.msgid = MAVLINK_MSG_ID_SET_VELOCITY_LIMITS;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_set_velocity_limits( float horizontal_speed_limit, float vertical_speed_limit, float yaw_rate_limit, short target_system, short target_component) {
        this.msgid = MAVLINK_MSG_ID_SET_VELOCITY_LIMITS;

        this.horizontal_speed_limit = horizontal_speed_limit;
        this.vertical_speed_limit = vertical_speed_limit;
        this.yaw_rate_limit = yaw_rate_limit;
        this.target_system = target_system;
        this.target_component = target_component;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_set_velocity_limits( float horizontal_speed_limit, float vertical_speed_limit, float yaw_rate_limit, short target_system, short target_component, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_SET_VELOCITY_LIMITS;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.horizontal_speed_limit = horizontal_speed_limit;
        this.vertical_speed_limit = vertical_speed_limit;
        this.yaw_rate_limit = yaw_rate_limit;
        this.target_system = target_system;
        this.target_component = target_component;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_set_velocity_limits(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_SET_VELOCITY_LIMITS;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

              
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_SET_VELOCITY_LIMITS - sysid:"+sysid+" compid:"+compid+" horizontal_speed_limit:"+horizontal_speed_limit+" vertical_speed_limit:"+vertical_speed_limit+" yaw_rate_limit:"+yaw_rate_limit+" target_system:"+target_system+" target_component:"+target_component+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_SET_VELOCITY_LIMITS";
    }
}
        