/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * 
 */
public class AIRLINK_EYE_IP_VERSION {
   public static final int AIRLINK_IP_V4 = 0; /*  | */
   public static final int AIRLINK_IP_V6 = 1; /*  | */
   public static final int AIRLINK_EYE_IP_VERSION_ENUM_END = 2; /*  | */
}