/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * 
 */
public class AIRLINK_EYE_TURN_INIT_TYPE {
   public static final int AIRLINK_TURN_INIT_START = 0; /*  | */
   public static final int AIRLINK_TURN_INIT_OK = 1; /*  | */
   public static final int AIRLINK_TURN_INIT_BAD = 2; /*  | */
   public static final int AIRLINK_EYE_TURN_INIT_TYPE_ENUM_END = 3; /*  | */
}