/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * 
 */
public class AIRLINK_EYE_GS_HOLE_PUSH_RESP_TYPE {
   public static final int AIRLINK_HPR_PARTNER_NOT_READY = 0; /*  | */
   public static final int AIRLINK_HPR_PARTNER_READY = 1; /*  | */
   public static final int AIRLINK_EYE_GS_HOLE_PUSH_RESP_TYPE_ENUM_END = 2; /*  | */
}