/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * 
 */
public class AIRLINK_EYE_HOLE_PUSH_TYPE {
   public static final int AIRLINK_HP_NOT_PENETRATED = 0; /*  | */
   public static final int AIRLINK_HP_BROKEN = 1; /*  | */
   public static final int AIRLINK_EYE_HOLE_PUSH_TYPE_ENUM_END = 2; /*  | */
}