/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Fuel types for use in FUEL_TYPE. Fuel types specify the units for the maximum, available and consumed fuel, and for the flow rates.
 */
public class MAV_FUEL_TYPE {
   public static final int MAV_FUEL_TYPE_UNKNOWN = 0; /* Not specified. Fuel levels are normalized (i.e. maximum is 1, and other levels are relative to 1). | */
   public static final int MAV_FUEL_TYPE_LIQUID = 1; /* A generic liquid fuel. Fuel levels are in millilitres (ml). Fuel rates are in millilitres/second. | */
   public static final int MAV_FUEL_TYPE_GAS = 2; /* A gas tank. Fuel levels are in kilo-Pascal (kPa), and flow rates are in milliliters per second (ml/s). | */
   public static final int MAV_FUEL_TYPE_ENUM_END = 3; /*  | */
}